export enum UserRole {
  ADMIN_GERAL = 'ADMIN_GERAL',
  ADMIN_UNIDADE = 'ADMIN_UNIDADE',
  SUPERVISOR = 'SUPERVISOR',
  OPERADOR = 'OPERADOR',
}

export enum SectorType {
  ESTOQUE = 'ESTOQUE',
  PRODUCAO = 'PRODUCAO',
  FRENTE_LOJA = 'FRENTE_LOJA',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  EXPEDICAO = 'EXPEDICAO',
}

export enum ProductionStatus {
  PENDENTE = 'PENDENTE',
  ENVIADO = 'ENVIADO',
  EM_PRODUCAO = 'EM_PRODUCAO',
  CONCLUIDO = 'CONCLUIDO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}

export enum TransferType {
  COMPRA_FORNECEDOR = 'COMPRA_FORNECEDOR',
  VENDA_INTERNA = 'VENDA_INTERNA',
  DEVOLUCAO_INTERNA = 'DEVOLUCAO_INTERNA',
  REAPROVEITAMENTO = 'REAPROVEITAMENTO',
  DESCARTE = 'DESCARTE',
}
